FROM ncarlier/mqtt:latest
LABEL org.freenas.interactive="false" 		\
      org.freenas.version="1"			\
      org.freenas.upgradeable="true"		\
      org.freenas.expose-ports-at-host="true"	\
      org.freenas.autostart="true"		\
      org.freenas.port-mappings="8083:8083/tcp"			\
